openapi: 3.0.3
info:
  title: Самокат. Облачный сервис ("NGENIX") - OpenAPI 3.0
  description: |-
    Описание API для взаимодействия с облачным сервисом NGENIX
  version: 1.0.12
tags:
  - name: videos
    description: Работа с видео в отзыве
paths:
  /video:
    post:
      tags: 
        - videos
      summary: Добавление видео
      description: Добавление видео при редактировании отзыва
      operationId: postVideo
      requestBody:
        content:
          multipart/form-data:  
            schema:
              type: object
              properties:
                files: 
                  type: array
                  items: 
                    type: string
                    format: binary
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Ошибка в запросе
        '500':
          description: Ошибка при обработке запроса на стороне сервера
  /video/{video_id}:
    get:
      tags: 
        - videos
      summary: Получение видео
      description: Получение видео по id
      operationId: getVideo
      parameters:
        - name: video_id
          in: path
          description: Id видео
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            multipart/form-data:
              schema:
                type: string
                format: binary
        '400':
          description: Ошибка в запросе
        '500':
          description: Ошибка при обработке запроса на стороне сервера
    delete:
      tags:
        - videos
      summary: Удаление видео
      description: Удаление видео при редактировании отзыва/удалении отзыва
      operationId: deleteVideo
      parameters:
        - name: video_id
          in: path
          description: Id of the video to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '400':
          description: Ошибка в запросе
        '500':
          description: Ошибка при обработке запроса на стороне сервера
components:
  schemas:
    Video:
      type: object
      properties:
        file_name:
          type: string
          example: Пользовательский_файл
        file:
          type: string
